enum ErrorTitles {
    ERROR_DEFAULT = 'ERROR DEL SERVIDOR',
    NOT_FOUND = 'RECURSO NO ENCONTRADO',
    ERROR_DATABASE = 'ERROR DE LA BASE DE DATOS',
    NOT_CREATED = 'RECURSO NO CREADO',
    ERROR_EMAIL = 'ERROR ENVIANDO EMAIL'
}

export default ErrorTitles;